// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT0FoQqIgMieYPIcXegvP4FArME27smpU',
    appId: '1:541546114635:web:07b4c24138f928037667ce',
    messagingSenderId: '541546114635',
    projectId: 'taskova-aa5d2',
    authDomain: 'taskova-aa5d2.firebaseapp.com',
    storageBucket: 'taskova-aa5d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXmrr7sT2lTu7t5vxZRr8YuGKBXaTsyA',
    appId: '1:541546114635:android:69622f72b75f32bd7667ce',
    messagingSenderId: '541546114635',
    projectId: 'taskova-aa5d2',
    storageBucket: 'taskova-aa5d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ytaNdkfT8CsagyaLl9lVACGUXd03Zyk',
    appId: '1:541546114635:ios:59e5700185f954557667ce',
    messagingSenderId: '541546114635',
    projectId: 'taskova-aa5d2',
    storageBucket: 'taskova-aa5d2.firebasestorage.app',
    androidClientId:
        '541546114635-n0dmsk5b2742k0qiju0er78qcl5b239g.apps.googleusercontent.com',
    iosClientId:
        '541546114635-vkuac0fhgao0hft0sc4eau8jo75290fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ytaNdkfT8CsagyaLl9lVACGUXd03Zyk',
    appId: '1:541546114635:ios:59e5700185f954557667ce',
    messagingSenderId: '541546114635',
    projectId: 'taskova-aa5d2',
    storageBucket: 'taskova-aa5d2.firebasestorage.app',
    androidClientId:
        '541546114635-n0dmsk5b2742k0qiju0er78qcl5b239g.apps.googleusercontent.com',
    iosClientId:
        '541546114635-vkuac0fhgao0hft0sc4eau8jo75290fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT0FoQqIgMieYPIcXegvP4FArME27smpU',
    appId: '1:541546114635:web:6ceac734b47a7c337667ce',
    messagingSenderId: '541546114635',
    projectId: 'taskova-aa5d2',
    authDomain: 'taskova-aa5d2.firebaseapp.com',
    storageBucket: 'taskova-aa5d2.firebasestorage.app',
  );
}
